CREATE TABLE IF NOT EXISTS contacts
(
    `id` String,
    `date_entered` DateTime,
    `date_modified` DateTime,
    `modified_user_id` String,
    `created_by` String,
    `description` String,
    `deleted` String,
    `assigned_user_id` String,
    `salutation` String,
    `first_name` String,
    `last_name` String,
    `title` String,
    `department` String,
    `do_not_call` String,
    `phone_home` String,
    `phone_mobile` String,
    `phone_work` String,
    `phone_other` String,
    `phone_fax` String,
    `primary_address_street` String,
    `primary_address_city` String,
    `primary_address_state` String,
    `primary_address_postalcode` String,
    `primary_address_country` String,
    `alt_address_street` String,
    `alt_address_city` String,
    `alt_address_state` String,
    `alt_address_postalcode` String,
    `alt_address_country` String,
    `assistant` String,
    `assistant_phone` String,
    `lead_source` String,
    `reports_to_id` String,
    `birthdate` Date,
    `campaign_id` String,
    `joomla_account_id` String,
    `portal_account_disabled` String,
    `portal_user_type` String,
    `photo` String
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{cluster}/{shard}/gar/contacts', '{replica}')
ORDER BY id
SETTINGS index_granularity = 8192